export const Members = [
  {
    _id: "747758150144229527",
    name: "bera",
    tag: "9999",
    username: "bwea",
    avatar: "/Avatars/Static/Brea.png",
    dynamicAvatar: "/Avatars/Dynamic/Brea.gif",
    status: "dnd",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#000000",
    about: "moonlight",
    created: "Aug 25, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [
      {
        _id: "322846109712252928",
        name: "Forward Assault",
        icon: "/Avatars/Static/ForwardAssault.jpg",
        defaultChannel: "322846109712252928",
      },
    ],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "535459462622740511",
    name: "Lisoo",
    tag: "9169",
    username: "poorsa",
    avatar: "/Avatars/Static/default3.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#000f00",
    about: null,
    created: "Jan 17, 2019",
    themeColors: null,
    transparentProfile: false,
    servers: [
      {
        _id: "322846109712252928",
        name: "Forward Assault",
        icon: "/Avatars/Static/ForwardAssault.jpg",
        defaultChannel: "322846109712252928",
      },
    ],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "1060500137115385886",
    name: "Mehmet ❤ Asya",
    tag: "3034",
    username: "_imsunnybunny_",
    avatar: "/Avatars/Static/Mehmet ❤ Asya.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#292814",
    about: null,
    created: "Jan 05, 2023",
    themeColors: null,
    transparentProfile: false,
    servers: [
      {
        _id: "322846109712252928",
        name: "Forward Assault",
        icon: "/Avatars/Static/ForwardAssault.jpg",
        defaultChannel: "322846109712252928",
      },
    ],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "544711857429282826",
    name: "Ashir",
    tag: "0272",
    username: "normalasianguy",
    avatar: "/Avatars/Static/Ashir.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: "/Banners/Ashir.gif",
    bannerColor: "#000000",
    about: null,
    created: "Feb 19, 2019",
    themeColors: ["#061e31", "#745824"],
    transparentProfile: true,
    servers: [
      {
        _id: "322846109712252928",
        name: "Forward Assault",
        icon: "/Avatars/Static/ForwardAssault.jpg",
        defaultChannel: "322846109712252928",
      },
    ],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "294629958695911424",
    name: "a name",
    tag: "3528",
    username: "justausrnam",
    avatar: "/Avatars/Static/default1.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#FCA31D",
    about: null,
    created: "Mar 25, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [
      {
        _id: "322846109712252928",
        name: "Forward Assault",
        icon: "/Avatars/Static/ForwardAssault.jpg",
        defaultChannel: "322846109712252928",
      },
    ],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "116275390695079945",
    name: "Nadeko",
    tag: "6685",
    username: "nadeko",
    avatar: "/Avatars/Static/Nadeko.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: "Playing .h for help",
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Nov 25, 2015",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "155149108183695360",
    name: "Dyno",
    tag: "3861",
    username: "dyno",
    avatar: "/Avatars/Static/Dyno.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: "Playing dyno.gg | ?help",
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Mar 4, 2016",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "708218616625233960",
    name: "RÆÍÑ",
    tag: "4629",
    username: "rain",
    avatar: "/Avatars/Static/RÆÍÑ.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "May 8, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "708218616625233960",
    name: "RÆÍÑ",
    tag: "4629",
    username: "rain",
    avatar: "/Avatars/Static/RÆÍÑ.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "May 8, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "758053179693727854",
    name: "Marash",
    tag: "7999",
    username: "marash",
    avatar: "/Avatars/Static/default2.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Sep 22, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "282859044593598464",
    name: "ProBot ✨",
    tag: "5803",
    username: "probot",
    avatar: "/Avatars/Static/ProBot.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 19, 2017",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "506474218938957824",
    name: "Qioxyn",
    tag: "3588",
    username: "qioxyn",
    avatar: "/Avatars/Static/Qioxyn.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Oct 29, 2018",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "567703512763334685",
    name: "ProBot Prime ✨",
    tag: "6379",
    username: "probotprime",
    avatar: "/Avatars/Static/ProBot Prime.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Apr 16, 2019",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "914679594022477834",
    name: "Savage 😼",
    tag: "6379",
    username: "probotprime",
    avatar: "/Avatars/Static/default1.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Nov 29, 2021",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "270904126974590976",
    name: "Dank Memer",
    tag: "5192",
    username: "dankmemer",
    avatar: "/Avatars/Static/Dank Memer.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: 'Playing /help',
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Jan 17, 2017",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "791038510089502750",
    name: "\" ❥ζ͜͡KIRTI♡🌸",
    tag: "9250",
    username: "kirti",
    avatar: "/Avatars/Static/Kirti.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Dec 22, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "563434444321587202",
    name: "Maki",
    tag: "4920",
    username: "kirti",
    avatar: "/Avatars/Static/Maki.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Apr 22, 2019",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "159985870458322944",
    name: "MEE6",
    tag: "4876",
    username: "mee6",
    avatar: "/Avatars/Static/MEE6.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: 'Playing /characters',
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Mar 17, 2016",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "681532725546582030",
    name: "Luisa",
    tag: "9999",
    username: "luisa",
    avatar: "/Avatars/Static/Luisa.png",
    dynamicAvatar: null,
    status: "offline",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 24, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "923010592808239134",
    name: "sux",
    tag: "0999",
    username: "sux",
    avatar: "/Avatars/Static/sux.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Nov 10, 2019",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "529279270821036042",
    name: "Altayist『𐰚𐰚』",
    tag: "9999",
    username: "luisa",
    avatar: "/Avatars/Static/Altayist.png",
    dynamicAvatar: null,
    status: "idle",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 24, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "369169234544295936",
    name: "Nida Akaviri",
    tag: "7348",
    username: "asyate",
    avatar: "/Avatars/Static/asyate.png",
    dynamicAvatar: null,
    status: "dnd",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 24, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "769931144375304202",
    name: "Akseé",
    tag: "7348",
    username: "aksee",
    avatar: "/Avatars/Static/aksee.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 24, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "962479591367278662",
    name: "ali",
    tag: "7748",
    username: "ali",
    avatar: "/Avatars/Static/ali.png",
    dynamicAvatar: null,
    status: "online",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 24, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "922715819560017970",
    name: "zaha",
    tag: "7348",
    username: "aksee",
    avatar: "/Avatars/Static/zaha.png",
    dynamicAvatar: null,
    status: "idle",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 24, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
  {
    _id: "432715219560017901",
    name: "zaha",
    tag: "7348",
    username: "aksee",
    avatar: "/Avatars/Static/zaha.png",
    dynamicAvatar: null,
    status: "idle",
    customStatus: null,
    badges: [],
    banner: null,
    bannerColor: "#eeeeee",
    about: null,
    created: "Feb 24, 2020",
    themeColors: null,
    transparentProfile: false,
    servers: [],
    friends: [],
    isDeleted: false,
  },
];

export function getUsers() {
  return Members.filter((m) => m);
}

export function getUser(id) {
  return Members.find((m) => m._id === id);
}
